config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'rooms/new'
  get 'rooms/create'
  get 'rooms/description'
  get 'rooms/location'
  get 'rooms/update'
  get "search" => "searches#search"


  devise_for :users, controllers: {   registrations: 'users/registrations',sessions: 'users/sessions' }
  get 'nomads/top'
  get 'rooms/search'
  get '/users/sign_in'
  get '/users/sign_up'
  get 'rooms/new'
  get 'reservations/show'
  get 'rooms/search'
  get 'rooms/posts' => 'rooms#index'
  get 'users/registrations/edit'
  get 'users/profile' => 'users#profile'
  get '/reservations' => 'reservations#index'
  post 'reservations/confirm' # 確認画面
  post 'reservation/back' # 確認画面から「入力画面に戻る」をクリックしたとき
  post 'reservations/complete' # 完了画面



  resource :rooms


  resources :rooms, except: [:edit] do
    member do
      get 'rooms/new'
      get 'rooms/posts' => 'rooms#index'
      get 'description'
      post 'reservations/confirm' # 確認画面
      post 'reservation/back' # 確認画面から「入力画面に戻る」をクリックしたとき
      post 'reservations/complete' # 完了画面
    
    end

  resources :reservations

  get '/reservations' => 'reservations#index'
  post 'reservations/confirm' # 確認画面
  post 'reservation/back' # 確認画面から「入力画面に戻る」をクリックしたとき
  post 'reservations/complete' # 完了画面
  end

  resource :rooms do
    resource :reservations
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  def total
    room.single_rate * number_of_people * (end_date - start_date).to_i
  end

  def days
    (end_date - start_date).to_i + 1
  end

  def stay
    (end_date - start_date).to_i
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!

    before_action :permit_params, only: :confirm
    


    def index
      @reservations = Reservation.all
      #binding.pry
      @rooms = Room.all
      #@reservations = @rooms
      #binding.pry
    end

    def new
      session.delete(:reservation)
      @reservation = Reservation.new
      @room = Room.find(params[:room_id])
      render 'reservations/confirm'
    end

    def back
      @reservation = Reservation.new(session[:reservation])
      session.delete(:reservation)
      render partial:"form"
    end

    def confirm
      @room = Room.find(params[:room_id])
      @reservation = Reservation.new(@attr)
      session[:reservation] = @reservation
      session[:room] = @room
      if @reservation.invalid?
        render 'reservations/confirm'
      end
    end

    def complete
      Reservation.create!(session[:reservation])
      session.delete(:reservation)
    end

    def create
      @room = Room.find(params[:room_id])
        @reservation = Reservation.new
        @start_date = Date.parse(reservation_params[:start_date])
        @end_date = Date.parse(reservation_params[:end_date])
        @days = (end_date - start_date).to_i + 1
        @reservation = current_user.reservations.build(reservation_params)
        @reservation.user_id = current_user.id
        @reservation.room = @room
        @reservation.room_id = @room_id
        #@reservation.single_rate = room.single_rate
        #@reservation.total = room.single_rate * days * number_of_people
        @reservation.save
  
        flash[:notice] = "予約が完了しました。"
      redirect_to :rooms_posts
    end

    private
      def reservation_params
        params.require(:reservation).permit(:start_date, :end_date, :number_of_people, :room_id, :room_name, :user_id, :room_image_name)
      end

      def permit_params
        @attr = params.permit(:start_date, :end_date, :number_of_people, :room_id, :room_name, :user_id, :room_image_name)
      end

      def room_params
        params.require(:room).permit(:id, :image_name, :name)
      end
    end

app/views/reservations/_form.html.erb
<%= form_with model:@reservation , url: reservations_confirm_path do |f| %>
  <div class="card">
    <div class="card-content">
      <div class="content">
          <div class="field is-horizontal">
            <div class="field-body">
                <div class="field">
                <p class="control is-expanded has-icons-left">
                    <%= f.date_field :start_date, placeholder: "開始日", class: "input is-primary is-rounded" %>
                </p>
                </div>
                <div class="field">
                <p class="control is-expanded has-icons-left has-icons-right">
                    <%= f.date_field :end_date, placeholder: "終了日", class: "input is-primary is-rounded" %>
                </p>
                </div>
                <div class="field">
                <p class="control is-expanded has-icons-left has-icons-right">
                    <%= f.number_field :number_of_people, placeholder: "宿泊人数", class: "input is-primary is-rounded" %>
                </p>
                </div>
                <%= f.hidden_field :room_id, value: @room.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.submit "予約内容確認へ", class: "button is-danger is-fullwidth m-t-10 m-b-10"  %>
                <i> ＊予約ボタンが反応しない時はリロードしてください。</i>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  $(document).on('turbolinks:load', function() {
  function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }
  $(function() {
    unavailableDates = [];
    $.ajax({
      dateTyp: 'json',
      success: function(data) {
        $.each(data, function(arrID, arrValue) {
            for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
              unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
            }
        });
        });
      }
    });
  });
  });
</script>

app/views/reservations/complete.html.erb
<h3>ご予約ありがとうございました！</h3>
<%= link_to "TOPへ戻る", nomads_top_path %>

app/views/reservations/confirm.html.erb
<h3>予約確認</h3>
<table>
    <thead>
      <tr align="center">
        <th>予約する部屋</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>日数</th>
        <th>人数</th>
        <th>合計料金</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @room.name %></td>
        <td><%= @reservation.start_date %></td>
        <td><%= @reservation.end_date %></td>
        <td><%= @reservation.stay %>泊<%= @reservation.days %>日</td>
        <td><%= @reservation.number_of_people %>人</td>
        <td>￥<%= @reservation.total %></td>
      </tr>
    </tbody>
</table>


<%= link_to :back do %>
  <button>入力画面に戻る</button>
<% end %>

<%= form_with model:@reservation, method: :post, url: reservations_complete_path do |form| %>
	<%= form.submit '予約確定' %>
<% end %>

app/views/reservations/index.erb
<!--予約済みルーム一覧-->

<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
    </tr>
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= image_tag (reservation.room.image_name.url) %></td>
          <td><%= reservation.room.name %></td>
          <td>¥<%= reservation.total %></td>
          <td><%= reservation.start_date %></td>
          <td><%= reservation.end_date %></td>
          <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/reservation.html.erb
<!--予約済みルーム一覧-->

<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          ルーム画像
        </td>
        <td>
          ルーム名
        </td>
        <td>
          ルーム紹介
        </td>
        <td>
          合計料金
        </td>
        <td>
          開始日
        </td>
        <td>
          終了日
        </td>
        <td>
          予約確定日
        </td>
      </tr>
    </tbody>
  </table>
</div>