config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'rooms/new'
  get 'rooms/create'
  get 'rooms/description'
  get 'rooms/location'
  get 'rooms/update'
  get "search" => "searches#search"


  devise_for :users, controllers: {   registrations: 'users/registrations',sessions: 'users/sessions' }
  get 'nomads/top'
  get 'rooms/search'
  get '/users/sign_in'
  get '/users/sign_up'
  get 'rooms/new'
  get 'reservations/show'
  get 'rooms/search'
  get 'rooms/posts' => 'rooms#index'
  get 'users/registrations/edit'
  get 'users/profile' => 'users#profile'
  get '/reservations' => 'reservations#index'
  post 'reservations/confirm' # 確認画面
  post 'reservation/back' # 確認画面から「入力画面に戻る」をクリックしたとき
  post 'reservations/complete' # 完了画面



  resource :rooms


  resources :rooms, except: [:edit] do
    member do
      get 'rooms/new'
      get 'rooms/posts' => 'rooms#index'
      get 'description'
      post 'reservations/confirm' # 確認画面
      post 'reservation/back' # 確認画面から「入力画面に戻る」をクリックしたとき
      post 'reservations/complete' # 完了画面
    
    end

  resources :reservations

  get '/reservations' => 'reservations#index'
  post 'reservations/confirm' # 確認画面
  post 'reservation/back' # 確認画面から「入力画面に戻る」をクリックしたとき
  post 'reservations/complete' # 完了画面
  end

  resource :rooms do
    resource :reservations
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def index

  end

  def search
    if params[:keyword].present?
      @rooms = Room.where(["name LIKE? OR introduce LIKE? OR address LIKE?", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%"])
    elsif params[:area].present?
      @rooms = Room.where(["address like?","%#{params[:area]}%"])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">検索結果一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>部屋番号</th>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.id %></td>
          <td><%= image_tag (room.image_name.url) %></td>
          <td><%= room.name %></td>
          <td><%= room.introduce %></td>
          <td><%= room.single_rate %></td>
          <td><%= room.created_at.to_s(:datetime_jp) %></td>
          <td><%= link_to "詳細・予約", room_path(room.id) %></td>
          <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>